# -------------------------------------------------------------------------------------
# Author Configuration
# -------------------------------------------------------------------------------------

name = "Jian YE"
email = "18817571704@163.com"
link = "https://github.com/jianye0428"
avatar = "/images/favicon/jian_icon.png"
